postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=redmine
    volumes:
        - /srv/docker/redmine/postgresql:/var/lib/postgresql
    restart: always

redmine:
    image: redmine
    links:
        - postgres:postgres
    ports:
        - 3000:3000
    volumes:
        - /srv/docker/redmine/redmine:/home/redmine/data
    restart: always
